# Converts lua from the old to new D3 API

def EnumerateDirectory(dir)
	result = []

	Dir.entries(dir).select { |entry| 
		if (entry =='.' || entry == '..')
			next
		end
		if File.directory?(File.join(dir, entry).gsub("/", "\\"))
			result += EnumerateDirectory(File.join(dir, entry).gsub("/", "\\"))
		elsif entry.end_with?(".lua")
			result.push(File.join(dir, entry))
		end
	}

	return result
end

files = EnumerateDirectory("Lua")

files.each {|file| # For each include file we found		
	puts "'#{file}'"
	fileResult = []
	bFile = File.new(file, "r")
	while (line = bFile.gets)
		line = line.gsub("Network_Out_Block_Set", "")
		line = line.gsub("Client_Get_Table", "Client.getall")
		line = line.gsub("Client_Get_Map_ID", "Client.getmap")
		line = line.gsub("Client_Get_IP", "Client.getip")
		line = line.gsub("Client_Get_Login_Name", "Client.getloginname")
		line = line.gsub("Client_Get_Logged_In", "Client.isloggedin")
		line = line.gsub("Client_Get_Entity", "Client.getentity")
		line = line.gsub("Build_Mode_Set", "BuildMode.set")
		line = line.gsub("Build_Mode_Get", "BuildMode.get")
		line = line.gsub("Build_Mode_State_Set", "BuildMode.setstate")
		line = line.gsub("Build_Mode_State_Get", "BuildMode.getstate")
		line = line.gsub("Build_Mode_Coordinate_Set", "BuildMode.setcoordinate")
		line = line.gsub("Build_Mode_Coordinate_Get", "BuildMode.getcoordinate")
		line = line.gsub("Build_Mode_Long_Set", "BuildMode.getlong")
		line = line.gsub("Build_Mode_Long_Get", "BuildMode.setlong")
		line = line.gsub("Build_Mode_Float_Set", "BuildMode.setfloat")
		line = line.gsub("Build_Mode_Float_Get", "BuildMode.getfloat")
		line = line.gsub("Build_Mode_String_Set", "BuildMode.getstring")
		line = line.gsub("Build_Mode_String_Get", "BuildMode.setstring")
		line = line.gsub("Build_Line_Player", "Build.line")
		line = line.gsub("Build_Box_Player", "Build.box")
		line = line.gsub("Build_Sphere_Player", "Build.sphere")
		line = line.gsub("Build_Rank_Box", "Build.rankbox")
		line = line.gsub("Entity_Get_Table", "Entity.getall")
		line = line.gsub("Entity_Add", "Entity.create") 
		line = line.gsub("Entity_Delete", "Entity.delete")
		line = line.gsub("Entity_Get_Player", "Entity.getplayer")
		line = line.gsub("Entity_Get_Map_ID", "Entity.getmap")
		line = line.gsub("Entity_Get_X", "Entity.getposition")
		line = line.gsub("Entity_Get_Rotation", "Entity.getrotation")
		line = line.gsub("Entity_Get_Look", "Entity.getlook")
		line = line.gsub("Entity_Resend", "Entity.resend")
		line = line.gsub("Entity_Message_2_Clients", "Entity.sendmessage")
		line = line.gsub("Entity_Displayname_Get", "Entity.getdisplayname")
		line = line.gsub("Entity_Displayname_Set", "Entity.setdisplayname")
		line = line.gsub("Entity_Position_Set", "Entity.setposition")
		line = line.gsub("Entity_Kill", "Entity.kill")
		line = line.gsub("Player_Get_Table", "Player.getall")
		line = line.gsub("Player_Get_Prefix", "Player.getprefix")
		line = line.gsub("Player_Get_Name", "Player.getname")
		line = line.gsub("Player_Get_Suffix", "Player.getsuffix")
		line = line.gsub("Player_Get_IP", "Player.ip")
		line = line.gsub("Player_Get_Rank", "Player.rank")
		line = line.gsub("Player_Get_Online", "Player.online")
		line = line.gsub("Player_Get_Ontime", "Player.ontime")
		line = line.gsub("Player_Get_Mute_Time", "Player.mutetime")
		line = line.gsub("Player_Set_Rank", "Player.setrank")
		line = line.gsub("Player_Kick", "Player.kick")
		line = line.gsub("Player_Ban", "Player.ban")
		line = line.gsub("Player_Unban", "Player.unban")
		line = line.gsub("Player_Stop", "Player.stop")
		line = line.gsub("Player_Unstop", "Player.unstop")
		line = line.gsub("Player_Mute", "Player.mute")
		line = line.gsub("Player_Unmute", "Player.unmute")
		line = line.gsub("Map_Get_Table", "Map.getall")
		line = line.gsub("Map_Block_Change", "Map.setblock")
		line = line.gsub("Map_Block_Change_Client", "Map.setblockclient")
		line = line.gsub("Map_Block_Change_Player", "Map.setblockplayer")
		line = line.gsub("Map_Block_Move", "Map.moveblock")
		line = line.gsub("Map_Block_Get_Type", "Map.getblock")
		line = line.gsub("Map_Block_Get_Rank", "Map.getrank")
		line = line.gsub("Map_Block_Get_Player_Last", "Map.getplayer")
		line = line.gsub("Map_Get_Name", "Map.name")
		line = line.gsub("Map_Get_Unique_ID", "Map.uuid")
		line = line.gsub("Map_Get_Directory", "Map.directory")
		line = line.gsub("Map_Get_Rank_Build", "Map.buildrank")
		line = line.gsub("Map_Get_Rank_Show", "Map.showrank")
		line = line.gsub("Map_Get_Rank_Join", "Map.joinrank")
		line = line.gsub("Map_Get_Dimensions", "Map.size")
		line = line.gsub("Map_Get_Spawn", "Map.spawn")
		line = line.gsub("Map_Get_Save_Intervall", "Map.saveinterval")
		line = line.gsub("Map_Set_Name", "Map.setname")
		line = line.gsub("Map_Set_Directory", "Map.setdirectory")
		line = line.gsub("Map_Set_Rank_Build", "Map.setbuildrank")
		line = line.gsub("Map_Set_Rank_Join", "Map.setjoinrank")
		line = line.gsub("Map_Set_Rank_Show", "Map.setshowrank")
		line = line.gsub("Map_Set_Spawn", "Map.setspawn")
		line = line.gsub("Map_Set_Save_Intervall", "Map.setsaveinterval")
		line = line.gsub("Map_Add", "Map.add")
		line = line.gsub("Map_Action_Add_Resize", "Map.resize")
		line = line.gsub("Map_Action_Add_Save", "Map.save")
		line = line.gsub("Map_Action_Add_Fill", "Map.fill")
		line = line.gsub("Map_Action_Add_Delete", "Map.delete")
		line = line.gsub("Map_Resend", "Map.resend")
		line = line.gsub("Map_Export", "Map.export")
		line = line.gsub("Map_Import", "Map.import")
		line = line.gsub("Map_Export_Get_Size", "Map.exportsize")
		line = line.gsub("Block_Get_Table", "Block.getall")
		line = line.gsub("Block_Get_Name", "Block.name")
		line = line.gsub("Block_Get_Rank_Place", "Block.placerank")
		line = line.gsub("Block_Get_Rank_Delete", "Block.deleterank")
		line = line.gsub("Block_Get_Client_Type", "Block.clienttype")
		line = line.gsub("CreateGlobalBlock", "CPE.createblockdef")
		line = line.gsub("DeleteGlobalBlock", "CPE.deleteblockdef")
		line = line.gsub("CreateClientBlock", "CPE.createclientblockdef")
		line = line.gsub("DeleteClientBlock", "CPE.deleteclientblockdef")
		line = line.gsub("Rank_Get_Table", "Rank.getall")
		line = line.gsub("Rank_Add", "Rank.add")
		line = line.gsub("Rank_Delete", "Rank.delete")
		line = line.gsub("Rank_Get_Name", "Rank.getname")
		line = line.gsub("Rank_Get_Prefix", "Rank.getprefix")
		line = line.gsub("Rank_Get_Suffix", "Rank.getsuffix")
		line = line.gsub("Rank_Get_Root", "Rank.getroot")
		line = line.gsub("Teleporter_Get_Table", "Teleporter.getall")
		line = line.gsub("Teleporter_Add", "Teleporter.add")
		line = line.gsub("Teleporter_Delete", "Teleporter.delete")
		line = line.gsub("Teleporter_Get_Box", "Teleporter.getlocation")
		line = line.gsub("Teleporter_Get_Destination", "Teleporter.getdestination")
		line = line.gsub("System_Message_Network_Send_2_All", "System.msgAll")
		line = line.gsub("System_Message_Network_Send", "System.msg")
		line = line.gsub("Files_File_Get", "System.getfile")
		line = line.gsub("Files_Folder_Get", "System.getfolder")
		line = line.gsub("Event_Add", "System.addEvent")
		line = line.gsub("Event_Delete", "System.deleteEvent")
		line = line.gsub("Client_Get_Extensions", "CPE.getsrvexts")
		line = line.gsub("Client_Get_Extension", "CPE.getexts")
		line = line.gsub("CPE_Selection_Cuboid_Add", "CPE.addselection")
		line = line.gsub("CPE_Selection_Cuboid_Delete", "CPE.deleteselection")
		line = line.gsub("CPE_Get_Held_Block", "CPE.getheld")
		line = line.gsub("CPE_Set_Held_Block", "CPE.setheld")
		line = line.gsub("CPE_Map_Set_Env_Colors", "CPE.setenvcolors")
		line = line.gsub("CPE_Client_Set_Block_Permissions", "CPE.setblockperms")
		line = line.gsub("Map_Env_Apperance_Set", "CPE.setmapenv")
		line = line.gsub("CPE_Client_Hackcontrol_Send", "CPE.setclienthacks")
		line = line.gsub("Hotkey_Add", "CPE.addhotkey")
		line = line.gsub("Hotkey_Delete", "CPE.removehotkey")
		line = line.gsub("Map_Hackcontrol_Set", "CPE.setmaphacks")
		line = line.gsub("CPE_Model_Change", "CPE.setmodel")
		line = line.gsub("CPE_Set_Weather", "CPE.setweather")
		fileResult.push(line)
	end
	bFile.close()

	bFile = File.new(file, "w+")
	fileResult.each { |line| 
		bFile.puts(line)
	}
	bFile.close()
	
}

puts "Files cleaned."