# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Program Files\JetBrains\CLion 2020.3.2\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Program Files\JetBrains\CLion 2020.3.2\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Documents\git\D3PP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Documents\git\D3PP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"D:\Program Files\JetBrains\CLion 2020.3.2\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"D:\Program Files\JetBrains\CLion 2020.3.2\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Documents\git\D3PP\CMakeFiles D:\Documents\git\D3PP\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Documents\git\D3PP\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named D3PP

# Build rule for target.
D3PP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 D3PP
.PHONY : D3PP

# fast build rule for target.
D3PP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/build
.PHONY : D3PP/fast

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/main.cpp.s
.PHONY : main.cpp.s

src/Block.obj: src/Block.cpp.obj

.PHONY : src/Block.obj

# target to build an object file
src/Block.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Block.cpp.obj
.PHONY : src/Block.cpp.obj

src/Block.i: src/Block.cpp.i

.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s

.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/Files.obj: src/Files.cpp.obj

.PHONY : src/Files.obj

# target to build an object file
src/Files.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Files.cpp.obj
.PHONY : src/Files.cpp.obj

src/Files.i: src/Files.cpp.i

.PHONY : src/Files.i

# target to preprocess a source file
src/Files.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Files.cpp.i
.PHONY : src/Files.cpp.i

src/Files.s: src/Files.cpp.s

.PHONY : src/Files.s

# target to generate assembly for a file
src/Files.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Files.cpp.s
.PHONY : src/Files.cpp.s

src/Logger.obj: src/Logger.cpp.obj

.PHONY : src/Logger.obj

# target to build an object file
src/Logger.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Logger.cpp.obj
.PHONY : src/Logger.cpp.obj

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Network.obj: src/Network.cpp.obj

.PHONY : src/Network.obj

# target to build an object file
src/Network.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Network.cpp.obj
.PHONY : src/Network.cpp.obj

src/Network.i: src/Network.cpp.i

.PHONY : src/Network.i

# target to preprocess a source file
src/Network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Network.cpp.i
.PHONY : src/Network.cpp.i

src/Network.s: src/Network.cpp.s

.PHONY : src/Network.s

# target to generate assembly for a file
src/Network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Network.cpp.s
.PHONY : src/Network.cpp.s

src/TaskScheduler.obj: src/TaskScheduler.cpp.obj

.PHONY : src/TaskScheduler.obj

# target to build an object file
src/TaskScheduler.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/TaskScheduler.cpp.obj
.PHONY : src/TaskScheduler.cpp.obj

src/TaskScheduler.i: src/TaskScheduler.cpp.i

.PHONY : src/TaskScheduler.i

# target to preprocess a source file
src/TaskScheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/TaskScheduler.cpp.i
.PHONY : src/TaskScheduler.cpp.i

src/TaskScheduler.s: src/TaskScheduler.cpp.s

.PHONY : src/TaskScheduler.s

# target to generate assembly for a file
src/TaskScheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/TaskScheduler.cpp.s
.PHONY : src/TaskScheduler.cpp.s

src/Utils.obj: src/Utils.cpp.obj

.PHONY : src/Utils.obj

# target to build an object file
src/Utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Utils.cpp.obj
.PHONY : src/Utils.cpp.obj

src/Utils.i: src/Utils.cpp.i

.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s

.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\D3PP.dir\build.make CMakeFiles/D3PP.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... D3PP
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... src/Block.obj
	@echo ... src/Block.i
	@echo ... src/Block.s
	@echo ... src/Files.obj
	@echo ... src/Files.i
	@echo ... src/Files.s
	@echo ... src/Logger.obj
	@echo ... src/Logger.i
	@echo ... src/Logger.s
	@echo ... src/Network.obj
	@echo ... src/Network.i
	@echo ... src/Network.s
	@echo ... src/TaskScheduler.obj
	@echo ... src/TaskScheduler.i
	@echo ... src/TaskScheduler.s
	@echo ... src/Utils.obj
	@echo ... src/Utils.i
	@echo ... src/Utils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

